on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  
     
      - name: "Login to Docker hub"
        run: docker login --username ${{ secrets.DOCKER_NAME }} --password ${{secrets.DOCKER_TOKEN }}

      - name: "Bulding dockers jjjjj"  
        run: docker build -t ${{ secrets.DOCKER_NAME }}/jjjjj .

      - name: "Pushing to Docker hub"  
        run: docker push ${{ secrets.DOCKER_NAME }}/jjjjj



      
 
   
