on:
  push:
    branches:
      - master
      
  






jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - name: 'testing github action'
        run: pwd

      - name: 'testing pprinting'
        run: echo sayed

      - uses: actions/checkout@v3 

    

      - name: "login to Docker hub" 
        run: docker login --username ${{ secrets.DDOCKER }} --password ${{ secrets.TTOCKEN }}

      - name: "Bulding docker image"  
        run: docker build -t ${{ secrets.DDOCKER }}/image .

      - name: "pushing to Docker hub"
        run: docker push  ${{ secrets.DDOCKER }}/image  



       
