on:
  push:
    branches:
      - test
      
  






jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - name: 'testing github action'
        run: pwd

      - name: 'testing printing'
        run: echo sayed

      - uses: actions/checkout@v3 

    

      - name: "login to docker hub" 
        run: docker login --username ${{ secrets.DOCKER_NAME }} --password ${{ secrets.DOCKER_TOKEN }}

      - name: "Bulding docker image"  
        run: docker build -t ${{ secrets.DOCKER_NAME }}/image .

      - name: "pushing to Docker hub"
        run: docker push  ${{ secrets.DOCKER_NAME }}/image  



       
